
name: Deploy to Production

on:
  push:
    branches: ["master"]

jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: kciter/aws-ecr-action@v3
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: simplebank
          region: us-east-1
          tags: ${{ github.sha }}
          create_repo: false
          image_scanning_configuration: true
          set_repo_policy: true
          repo_policy_file: repo-policy.json
      - name: 'Load secret and save to app.env'
        run: aws secretsmanager get-secret-value --secret-id simple_bank --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > app.env

